### ISSUE TITLE
在返回图片时候的报错

### ISSUE THREAD

**Issue by filegkyangmao** [1130600015/MidJourney_QQ#3]
java.lang.NullPointerException: null
        at com.zjs.mj.schedulings.SchedulingTask.parse(SchedulingTask.java:191) [classes!/:1.0.0]
        at com.zjs.mj.schedulings.SchedulingTask.request(SchedulingTask.java:139) [classes!/:1.0.0]
        at com.zjs.mj.schedulings.SchedulingTask.queryRecentJobs(SchedulingTask.java:115) [classes!/:1.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_362]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_362]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_362]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_362]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.27.jar!/:5.3.27]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_362]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_362]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_362]

**Comment by filegkyangmao** [comment]
解析recent Job失败

java.lang.NullPointerException: null
        at com.zjs.mj.schedulings.SchedulingTask.parse(SchedulingTask.java:191) [classes!/:1.0.0]
        at com.zjs.mj.schedulings.SchedulingTask.request(SchedulingTask.java:139) [classes!/:1.0.0]
        at com.zjs.mj.schedulings.SchedulingTask.queryRecentJobs(SchedulingTask.java:115) [classes!/:1.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_362]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_362]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_362]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_362]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.27.jar!/:5.3.27]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_362]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_362]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_362]

**Comment by jiashu1024** [comment]
> 解析recent Job失败
> 
> java.lang.NullPointerException: null at com.zjs.mj.schedulings.SchedulingTask.parse(SchedulingTask.java:191) [classes!/:1.0.0] at com.zjs.mj.schedulings.SchedulingTask.request(SchedulingTask.java:139) [classes!/:1.0.0] at com.zjs.mj.schedulings.SchedulingTask.queryRecentJobs(SchedulingTask.java:115) [classes!/:1.0.0] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_362] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_362] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_362] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_362] at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.3.27.jar!/:5.3.27] at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.27.jar!/:5.3.27] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_362] at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_362] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_362] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_362] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_362] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_362] at java.lang.Thread.run(Thread.java:750) [na:1.8.0_362]

这个错误应该不影响普通作图的结果，这是定时查mj接口，目的是发现那些被删除的任务。我刚简单修复了下这个bug，已经更新了，你可以重新拉取项目，尝试下是否还会出这个错
